### ISSUE TITLE
[STRENGTH] Update Tutorials with OAuth2

### ISSUE THREAD

**Issue by ghost** [meteor/tutorials#108]
Just got exited, because adding google OAuth2 to the todo-tutorial worked 100% intuitive, **better than expected** and with 0 redundant steps. Very good work.

* I saw `accounts-facebook` and thus used `meteor add accounts-google` -> worked as expected
* Started my todo app, a button "Google is not configured" shows up. Clicking suggests `meteor add google-config-ui` -> surprise, works better than expected
* Clicking the button now brings up a dialogue with instructions of how to setup OAuth2 @ google, and 2 fields for entering the data -> works better than expected.

This must now be included into the tutorials, as an additional topic/step (adding Facebook/Google/Twitter etc.).

**Comment by abernix** [comment]
I'm glad it worked so easily for you!  But this is outside the scope of this tutorial and if we added every Meteor feature to the tutorial then it wouldn't be a simple tutorial anymore.

Accounts are documented in [the Docs](https://docs.meteor.com/) and the [Guide](https://guide.meteor.com/) for those that are interested in more advanced concepts!
