### ISSUE TITLE
Explain the Intentional Additional Steps

### ISSUE THREAD

**Issue by ghost** [meteor/tutorials#109]
The tutorials intro section should contain a statement like this:

> **Important**: Those tutorials are not quick-starts which produce an app in 5 minutes. Instead, the tutorials contain **intentionally** additional steps, enabling this way a deeper understanding of Meteor and its project structure. You should use a free IDE like `Visual Studio Code`, `IntelliJ` ... (list of some IDEs)

**Comment by abernix** [comment]
We start off by explaining that we are building a Todos application and don't really say that you will be able to produce an app in five minutes – I'm not sure that's the expectation of someone following a tutorial.

We do show them how to produce a working app on the very first page, in less than 5 minutes, by encouraging them to play with the app right after running `meteor create ...` and starting the app.  Also, by roughly step 5, there is a functioning application.  Conceivably, this could happen within a relatively small number of minutes.  If we wanted them to have a working app as fast as humanly possible, we would just tell them to clone an existing app – but that is not the goal (nor would it be a tutorial anymore).

I also don't think we want to call this a "deeper understanding" of Meteor as there is much, much more to Meteor than the scope of this tutorial and presumably they have _little_ to _no_ understanding of Meteor coming into the tutorial.

Currently, the tutorial starts with:

> In this tutorial, we are going to create a simple app to manage a 'to do' list and collaborate with others on those tasks.

I might propose we add:

> By the end, you should have a basic understanding of Meteor and its project structure.

Also, we already suggest them to use "their favorite editor" and this isn't really a beginners guide to coding, so I'm not sure we need to make suggestions.
