### ISSUE TITLE
Latest todo app with angular giving some issue with ng-include

### ISSUE THREAD

**Issue by MohitSharma** [meteor/tutorials#11]
SyntaxError: missing ) after argument list
    document.body.setAttribute('ng-include', ''todos-list.ng.html'');

**Comment by stubailo** [comment]
Yes, this is a real bug: https://github.com/meteor/meteor/issues/5276

**Comment by MohitSharma** [comment]
Its working this way <body ng-app="simple-todos"

```
  ng-include="\'todos-list.ng.html\'"

  ng-controller="TodosListCtrl">  :)
```

**Comment by stubailo** [comment]
Yep I'm not going to make the workaround official in hopes that we can release a 1.2.0.2 very soon.

**Comment by MohitSharma** [comment]
That's great ! Thanks Sashko
