### ISSUE TITLE
"Where is the best place to put common code?"

### ISSUE THREAD

**Issue by ghost** [meteor/tutorials#110]
Starting to understand Meteor a bit better, I realize the the `imports` folder contains the **common** code (shared between server and client). 

This means that changing the name to something more descriptive would make this immediately clear (within the tutorials, and whenever working with Meteor).

Possible terms would be:

* shared
* common

Sometimes the best answer is given already within a question. Look at this:

> Where is the best place to put common code (used by client and server)?
https://forums.meteor.com/t/where-is-the-best-place-to-put-common-code-used-by-client-and-server/21573

Answer: `common code` is best placed into the `common` folder.

* client
* common
* server

This would be very descriptive, e.g.: `common/api`

**Comment by hwillson** [comment]
Hi @lazaridis-com - the `imports` directory has a more significant meaning than just holding common code (actually, it doesn't have to hold common code at all). For a detailed explanation of how the `imports` directory works, take a look at the [Application Structure](https://guide.meteor.com/structure.html) section of the Guide. In a nutshell - files located outside of the `imports` directory are loaded eagerly, whereas files located within `imports` are only loaded when imported using Meteor's ES2015 module support. I'll quote the Guide on why the `imports` directory is necessary at all:

> Since this is a new feature introduced in Meteor 1.3, you will find a lot of code online that uses the older, more centralized conventions built around packages and apps declaring global symbols. This old system still works, so to opt-in to the new module system, code must be placed inside the imports/ directory in your application. We expect a future release of Meteor will turn on modules by default for all code, because this is more aligned with how developers in the wider JavaScript community write their code.

The above being said, feature request meteor/meteor#8341 is currently tracking the possibility of getting rid of the `imports` directory completely. For now however, the `imports` name has to stay as is, if interested in leveraging Meteor's ES2015 module support.

As for where is the best place to put common code - well, there isn't really one answer to that question. It really depends on many factors (like if you're using Meteor's ES2015 module support), but the Guide's [Application Structure](https://guide.meteor.com/structure.html) section does a great job at running through the available options.

I'll close this for now - thanks!

**Comment by hwillson** [comment]
I think the main thing to keep in mind is that the tutorials discussed in this repo are intended to be simple to get started with, quick to get up and running with, and focused on giving a brief introduction to how Meteor works. Getting into the more detailed aspects of Meteor based application design (like best practices for storing/accessing common code) are likely much better suited for something like the [Meteor Guide](https://guide.meteor.com) and it's accompanying reference app, [Todos](https://github.com/meteor/todos). I'm not sure if keeping this discussion point open here is that helpful, but if you feel strongly otherwise, I'm happy to re-open.

**Comment by lazaridis-com** [comment]
@hwillson , yep, just open it please.

**Comment by abernix** [comment]
@hwillson's comments in https://github.com/meteor/tutorials/issues/110#issuecomment-286868208 are spot-on.  This issue is a Meteor issue, not a tutorial issue.

(See also #53.)
