### ISSUE TITLE
Move Blaze Tutorial to a Less Prominent Position

### ISSUE THREAD

**Issue by ghost** [meteor/tutorials#111]
The Blaze Tutorial should be either removed, or moved to a less prominent position, thus newcomers do not use it as a foundation for new projects.

It is a quite negative experience to see "Blaze" mentioned as the "first-choice", and to hit later on such information:

https://forums.meteor.com/t/next-steps-on-blaze-and-the-view-layer/13561

https://forums.meteor.com/t/link-to-document-that-blaze-is-discontinued-in-favor-of-react/14554/2

**Comment by abernix** [comment]
Currently the tutorial offers three view-layers, side-by-side, on the tutorial landing page.  While Blaze is the first button, we don't specifically call-out and state that it's "most recommended".  The `meteor create` tool does create Blaze by default, but this is not a tutorial decision, this is a Meteor decision.

If and when the time comes for Meteor to change its default view layer (and I think that's a worthy conversation to have), we can change the way things are represented here in the Tutorial, but this is a Meteor-first, Tutorial-second scenario that needs to play out and this issue doesn't provide much value until that's addressed on the Meteor side.
