### ISSUE TITLE
Automate Tutorial Updates

### ISSUE THREAD

**Issue by ghost** [meteor/tutorials#115]
Issue #93 showcases the need to automate the tutorials-site update (either a commit-hook, or a daily update). So, when a change is merged, the issue is closed by a `fixed` comment, and the site updated immediately or within max. a day.

Ideally, documentation is hosted in a way that the updates go live immediately, without further effort to implement automations (commit-hooks etc.)

**Comment by abernix** [comment]
We will evaluate the possibility of decoupling the Meteor Tutorials from the Homepage in the future, but for now an issue to track this here won't be helpful as it's not something the community can really help with (since it's an internal MDG application) and we already track this internally.
