### ISSUE TITLE
Typo in 3.4 Modify App component to get tasks from collection Code Snippet(React)

### ISSUE THREAD

**Issue by ReaganCuthbert** [meteor/tutorials#122]
In the `{{> DiffBox step="3.4" tutorialName="simple-todos-react"}}`  code snippet, there should be a render method with the same markup from `{{> DiffBox tutorialName="simple-todos-react" step="2.4"}}`.

Currently, there is isolated parenthesis and curly braces. This will result in an error to the console if someone placed it in their code.

**Comment by hwillson** [comment]
A new version of the react tutorial is being published, and will be live soon. Please try things out with the new version and post back if you're still encountering any issues. Thanks!
