### ISSUE TITLE
Step 11: Testing

### ISSUE THREAD

**Issue by 1beb** [meteor/tutorials#123]
Some people may copy and paste the entire box, it's unhelpful to exclude that last '}' especially for people not familiar with javascript or not having a toolchain that would otherwise notify them that a closing brace is the only problem. 

I'm referring to adding a '}' at the very end of the code box in example 11.4

**Comment by hwillson** [comment]
A new version of the react tutorial is being published, and will be live soon. Please try things out with the new version and post back if you're still encountering any issues. Thanks!
