### ISSUE TITLE
Tutorial content issue

### ISSUE THREAD

**Issue by abernix** [meteor/tutorials#126]
Moving here, as @theboman reported in meteor/meteor#8671...

---

The tutorial section of the website seems to be displaying the wrong content. 

https://www.meteor.com/tutorials/react/creating-an-app (same)
https://www.meteor.com/tutorials/react/components  (same)
https://www.meteor.com/tutorials/react/collections  (same)
https://www.meteor.com/tutorials/react/forms-and-events - wrong content showing creating your first app

**Comment by abernix** [comment]
This should be fixed thanks to https://github.com/meteor/tutorial-tools/commit/fed8781132c7faf53a65c9f2f79f0788ea9f1af4 and https://github.com/meteor/tutorials/commit/499d8f94912aaa8b6f7172b860ada2e52a7b7ff5.

Again, thanks for reporting this originally!  And please ping back if this problem still exists.

Glad to see so many people are using the tutorials that they notice and report the problems when they're broken! :wink:

/cc @pilarArr & @revati1 who reported in #127 and #128.

**Comment by theboman** [comment]
Thank you Jesse, I am a newbie I want to learn! Love the Meteor website. Love that you have Tutorials on it. Hope more tutorials come especially more dumbed down for newbies. It's hard to get accurate tutorials since the tech is moving so fast.
