### ISSUE TITLE
Change React Tutorial to utilize "prop-types" npm package

### ISSUE THREAD

**Issue by srobertson421** [meteor/tutorials#129]
Currently the React tutorials utilize the PropTypes import from the react package. This should be change to utilize the npm module "prop-types" instead per React's warning about it being deprecated.

**Comment by cfisher440** [comment]
Yes, this is for the Simple Todo app on the Task.jsx file. The imports need to be changed from

`import React, { Component, PropTypes } from 'react';`

to

```
import React, { Component } from 'react';
import PropTypes from 'prop-types';
```

**Comment by braneof** [comment]
For the current version of React this gives an error and fails. It's not just a warning anymore.

**Comment by hwillson** [comment]
We've decided to remove `PropTypes` from the react tutorial. A new version is being published, and will be live soon. Thanks!
