### ISSUE TITLE
React tutorial step 3 db is undefined

### ISSUE THREAD

**Issue by MattSturgeon** [meteor/tutorials#14]
Following through the react tutorial I found that `db` was not defined

```
db.tasks.insert({ text: "Hello world!", createdAt: new Date() });
// ReferenceError: db is not defined

Tasks.insert({ text: "Hello world!", createdAt: new Date() });
// Works just fine
```

**Comment by stubailo** [comment]
That should be typed in the mongo console, not in the meteor shell or browser console. It tells you how to open the mongo console right above there.

**Comment by MattSturgeon** [comment]
Oops! My bad, late night skim reading is my excuse.
