### ISSUE TITLE
create simple-todos does progress after downloading

### ISSUE THREAD

**Issue by teenangst** [meteor/tutorials#143]
After entering `create simple-todos` it gives me the progress bar which after reaching 100% goes to the spinning thing and it never finishes, I've run it 3 times and left it for hours and it still doesn't do anything, there are no files or directories that have been created.

I have previously used Meteor but my knowledge has basically gone since and I updated Meteor and deleted the previous tutorials I had got through `create`. I didn't have issues before.

**Comment by abernix** [comment]
I don't think this is specifically a problem with the tutorials.  Can you provide a little bit more information, and possibly some console output?  Have you tried re-installing Meteor?  The command to do that, on Unix, would be:

    curl https://install.meteor.com/ | sh

I'll try to help further, but you'd probably get more help by asking on the [Meteor forums](http://forums.meteor.com/).

**Comment by teenangst** [comment]
Seems to have fixed itself, it now does it in 5 minutes or so
