### ISSUE TITLE
React tutorial step 8: currentUser needs to be exported

### ISSUE THREAD

**Issue by t3db0t** [meteor/tutorials#148]
As it stands, ```currentUser``` is not defined/exported, and so the New Task input field never shows up. I think ```currentUser``` is supposed to be provided by Blaze, but I'm not sure exactly how that's supposed to work with the Blaze wrapper.

In any case, I got it to work as desired by adding ```currentUser``` to the withTracker export (see bug https://github.com/meteor/tutorials/issues/147)

```
export default withTracker(props => {
	return {
		tasks: Tasks.find({}, { sort: { createdAt: -1 } }).fetch(),
		incompleteCount: Tasks.find({ checked: { $ne: true } }).count(),
		currentUser: Meteor.user(),
	};
})(App);
```

**Comment by hwillson** [comment]
Thanks @t3db0t - I'm currently working on bringing the React tutorial up to date. Changes will be coming soon.

**Comment by hwillson** [comment]
A new version of the react tutorial is being published, and will be live soon. Thanks!
