### ISSUE TITLE
Followed the angular guide all the way, but fails to get security running (Mac)

### ISSUE THREAD

**Issue by aceymer** [meteor/tutorials#16]
After I have added the login system (blaze-template) I get the dropdown but nothing happens when I click it.
I followed the guide step by step..

Using the following packages:
accounts-password             1.1.4  Password support for accounts
accounts-ui                   1.1.6  Simple templates to add login widgets to...
angular                       1.0.4  Everything you need to use AngularJS in ...
autopublish                   1.0.4  (For prototyping only) Publish the entir...
blaze-html-templates          1.0.1  Compile HTML templates into reactive UI ...
ecmascript                    0.1.6  Compiler plugin that supports ES2015+ in...
es5-shim                      4.1.14  Shims and polyfills to improve ECMAScri...
jquery                        1.11.4  Manipulate the DOM using CSS selectors
meteor-base                   1.0.1  Packages that every Meteor app needs
mobile-experience             1.0.1  Packages for a great mobile user experience
mongo                         1.1.3  Adaptor for using MongoDB and Minimongo ...
session                       1.1.1  Session variable
standard-minifiers            1.0.2  Standard minifiers used with Meteor apps...
tracker                       1.0.9  Dependency tracker to allow reactive cal...
urigo:angular-blaze-template  0.1.0  Include Blaze templates in your angular-...

Files:
app.js

``` javascript
Tasks = new Mongo.Collection('tasks');

if (Meteor.isClient) {

  Accounts.ui.config({
    passwordSignupFields: "USERNAME_ONLY"
  });

  // This code only runs on the client
  angular.module('simple-todos',['angular-meteor']);

  function onReady() {
    angular.bootstrap(document, ['simple-todos']);
  }

  if (Meteor.isCordova)
    angular.element(document).on('deviceready', onReady);
  else
    angular.element(document).ready(onReady);

  angular.module('simple-todos').controller('TodosListCtrl', ['$scope', '$meteor',
    function ($scope, $meteor) {

      $scope.tasks = $meteor.collection(function() {
        return Tasks.find($scope.getReactively('query'), {sort: {createdAt: -1}})
      });

      $scope.addTask = function(newTask) {
        $scope.tasks.push( {
            text: newTask,
            createdAt: new Date(),             // current time
            owner: Meteor.userId(),            // _id of logged in user
            username: Meteor.user().username }  // username of logged in user
        );
      };

      $scope.$watch('hideCompleted', function() {
        if ($scope.hideCompleted)
          $scope.query = {checked: {$ne: true}};
        else
          $scope.query = {};
      });

      $scope.incompleteCount = function () {
        return Tasks.find({ checked: {$ne: true} }).count();
      };

    }]);
}

```

todos-list.ng.html:

``` html
<div class="container">
  <header>
    <h1>Todo List ( {{ incompleteCount() }} )</h1>

    <label class="hide-completed">
      <input type="checkbox" ng-model="$parent.hideCompleted"/>
      Hide Completed Tasks
    </label>

    <blaze-template name="loginButtons"></blaze-template>

    <!-- add a form below the h1 -->
    <form class="new-task"
          ng-submit="addTask(newTask); newTask='';"
          ng-show="$root.currentUser">
      <input ng-model="newTask" type="text"
             name="text" placeholder="Type to add new tasks" />
    </form>
  </header>

  <ul>
    <li ng-repeat="task in tasks" ng-class="{'checked': task.checked}">
      <button class="delete" ng-click="tasks.remove(task)">&times;</button>

      <input type="checkbox" ng-model="task.checked" class="toggle-checked" />

      <span class="text">
        <strong>{{task.username}}</strong> - {{task.text}}
      </span>
    </li>
  </ul>
</div>
```

**Comment by Urigo** [comment]
@aceymer Please check out the new tutorial, it should be fixed now.
Let me know if it doesn't.
