### ISSUE TITLE
Meteor React Tutorial for Todos-List

### ISSUE THREAD

**Issue by derrideanauthor** [meteor/tutorials#160]
Hi guys,

I recently found an issue when trying out the react tutorial and I'm not sure what is wrong. I followed it to the T and nothing renders (supposed to show an HTML list). This happens early on (at step 2). https://www.meteor.com/tutorials/react/components

These are the JavaScript errors I got:

`Uncaught TypeError: Cannot read property 'object' of undefined
    at Task.jsx (app.js:273)
    at fileEvaluate (modules-runtime.js:343)
    at require (modules-runtime.js:238)
    at App.jsx (app.js:130)
    at fileEvaluate (modules-runtime.js:343)
    at require (modules-runtime.js:238)
    at main.js (app.js:45)
    at fileEvaluate (modules-runtime.js:343)
    at require (modules-runtime.js:238)
    at app.js:287`

Thanks in advance. 

PS If you can recommend other Meteor React tutorials Id be very grateful!

**Comment by hwillson** [comment]
Have you tried the new version of the React tutorial? It was just updated yesterday, and no longer uses the `.jsx` extension for any files (which makes me think you're following an outdated version of the tutorial). Please give the [new tutorial a try](https://www.meteor.com/tutorials/react/creating-an-app), and post back if you notice any issues. Thanks!

**Comment by derrideanauthor** [comment]
Thanks @hwillson will give that a go 👍
