### ISSUE TITLE
Uncaught Error: Target container is not a DOM element, react tutorial

### ISSUE THREAD

**Issue by Boursler** [meteor/tutorials#175]
In the Meteor React tutorial after completing step 2.5, this error appears in the browser: Uncaught Error: Target container is not a DOM element. 
![image](https://user-images.githubusercontent.com/22327658/42052015-7c65854e-7ac2-11e8-9625-24ec1967d1be.png)

I copy-pasted my code from the tutorial entirely, and I created the following files: imports/ui/App.js, imports/ui/Task.js. 

I got the code to work by adding: ``` import './main.html'; ``` to main.js. If this is the proper fix, can this import statement be added to the tutorial? If not, is there a better alternative? I'm totally new to Meteor.

**Comment by dronda-t** [comment]
I got this error just now and was just about to post an issue until I saw this. Apparently every new meteor app comes with blaze so you have to run:
`meteor remove blaze-html-templates`
`meteor add static-html`

They specify it on the guide [here](https://guide.meteor.com/react.html#using-with-meteor) but it really should be in the tutorial.

**Comment by ghost** [comment]
Will chime in to say this was a pain in my butt as well and also found both solutions then came here to create an issue.

Seems like the rest of the tutorial isn't using blaze so I removed then added static-html as well.

**Comment by Gordin** [comment]
Same here, just wasted a lot of time figuring out what is wrong with the tutorial... Just posting this to link this with other issues so someone else maybe finds this faster...

People fixing this with the html import: https://github.com/meteor/simple-todos-react/commit/4459f38b759d17ade45da61e67265fb48e6f39c5
Someone else having this problem (not exactly the same, but I had this same error while playing around with the tutorial and trying to fix this): https://github.com/meteor/tutorials/issues/166

**Comment by danielocdh** [comment]
Aww man, I get stuck on "starting your app" after fixing this

**Comment by oleggromov** [comment]
+1 to all said above. I just installed Meteor for the first time, dug into the guide and on the second step ran into this issue. Let's fix that please :+1: It will be very helpful for everybody!

**Comment by abernix** [comment]
Fixed by #185.
