### ISSUE TITLE
Conflict with angular-templates and pbastowski:angular-babel

### ISSUE THREAD

**Issue by bwillacker** [meteor/tutorials#19]
On step 2 of the Angular tutorial (https://www.meteor.com/tutorials/angular/templates), immediately after adding the 'angular' package, my app crashed with the error:

=> Errors prevented startup:

   While determining active plugins:
   error: conflict: two packages included in the app (angular-templates and
   templating) are both trying to handle *.html
   error: conflict: two packages included in the app (pbastowski:angular-babel
   and ecmascript) are both trying to handle *.js

It was necessary for me to remove 'blaze-html-templates' and 'ecmascript' packages to continue with the tutorial.

Let me know if you want me to do a PR and add a step to remove these packages in coordination with 'meteor add angular'

**Comment by Urigo** [comment]
@bwillacker thanks for the catch, I've updated the tutorial to add the following instructions:

```
meteor remove blaze-html-templates
meteor remove ecmascript
```

**Comment by bwillacker** [comment]
Thanks @Urigo! Appreciate all that you do for the community!
