### ISSUE TITLE
Step 8 (User Accounts) of the React tutorial doesn't work if you create your project with `meteor create --react`.

### ISSUE THREAD

**Issue by interfect** [meteor/tutorials#196]
I'm trying to use the Meteor React tutorial, but it assumes a vanilla `meteor create`, and not `meteor create --react` like I did.

It mostly works, until step 8 where I want to do user accounts. It tells me to `meteor add accounts-ui accounts-password`. The `accounts-ui` package won't actually work. In the browser console I get:

```
Error: jQuery not found dombackend.js:8:8
TypeError: Package.blaze is undefined
spacebars.js:22:13
TypeError: Package.blaze is undefined
templating-runtime.js:18:13
TypeError: Package['templating-runtime'] is undefined
templating.js:14:16
TypeError: Package['templating-runtime'] is undefined
accounts-ui-unstyled.js:21:16
TypeError: Accounts.ui is undefinedaccounts-config.js:3
```

To fix this I need to `meteor add jquery`. Apparently the `jquery` Atmosphere package is required for Blaze to work, and it isn't recognized as a transitive dependency of accounts-ui or installed by default in the base `meteor create --react` package.

This should be noted in the tutorial somehow, which is where people will come to try to get `accounts-ui` working under React.

**Comment by sebakerckhof** [comment]
Thanks for reporting. This is an oversight from the last 1.8.3 release, which removes the hard dependency on jquery in blaze (because theoretically you can use different backends). So theoretically this is correct, but in reality most people will need to add jquery, especially for the tutorial's purposes.

The tutorials are currently being rewritten and the new one will likely start from `meteor create --react` like you did, which will then also include instructions to add jquery once you add a package that depends on blaze.

cc @leonardoventurini

**Comment by leonardoventurini** [comment]
Exactly, they are being rewritten, it already starts out by using the `--react` flag. They will also use React Hooks.

**Comment by JasonZStanley** [comment]
While the docs are being rewritten I think it would be beneficial to add a line about this. 

Perhaps change:

> Currently, this UI component uses Blaze, Meteor's default UI engine. In the future, there might also be a React-specific component for this.

To:

> Currently, this UI component uses Blaze, Meteor's default UI engine. In the future, there might also be a React-specific component for this. If you built your app with the --react flag you will need to install jQuery to complete this section. You can do that by running `meteor npm install jquery`

Something like this would be a small change which removes any friction which developers would face when running through the tutorial.

**Comment by leonardoventurini** [comment]
@JasonZStanley In the new version, we build the login form without the blaze templates. Please take a look [here](https://github.com/meteor/simple-todos-react/blob/tortilla-master/.tortilla/manuals/views/step6.md) and tell us what you think. Every feedback is welcome.

**Comment by leonardoventurini** [comment]
The tutorials for React are almost done being rewritten, every feedback was received and appreciated, please let me know any other issue.

Worth highlighting that the new tutorial will not rely on the Blaze templates present in `accounts-ui` package, perhaps in the future we add a small React library to the package instead to fulfill that role.

Thanks.
