### ISSUE TITLE
App not running on localhost:3000

### ISSUE THREAD

**Issue by rogl4784** [meteor/tutorials#20]
Hey guys and gals,

I installed Meteor in Unix with curl https://install.meteor.com/ | sh.  I tried to view the simple-todos app on port 3000, but nothing came up. On Lubuntu (Linux), it didn't create the simple-todos folder.  

It could be me being a rookie-jabroni to Meteor, but just thought I would mention it!  Have a good one.

**Comment by stubailo** [comment]
You mean on Linux you were able to run the `meteor create` command, and it printed output to the terminal, but accessing localhost:3000 in your web browser didn't work?

**Comment by rogl4784** [comment]
Accessing through web browser on localhost:3000 didn’t work on Unix.  For Linux, I didn’t see simple-todo folder install in any directory, so I didn't get to do a browser test.

**Comment by stubailo** [comment]
did you run all of the commands in the first step of the tutorial? there are a few things you need to do between installing meteor and seeing the simple-todos app in your browser.

https://www.meteor.com/tutorials/blaze/creating-an-app

**Comment by mwhite454** [comment]
I'm not sure if I'm having the same issue, rogl4784, but I am unable to get past even the initial steps. I installed meteor (got success msg in terminal: Meteor 1.2.1 has been installed in your home directory (~/.meteor).) 
Next I went to the directory where I wanted to install the app and ran: meteor create simple-todos
Getting this success message - Created a new Meteor app in 'simple-todos'.
I changed to the simple-todos app directory and ran meteor --port 8000 because I had another test app running on 3000. I got a long string of errors so killed the session, as well as my other app and tried to restart meteor tutorial on port 3000, getting the same set of errors:

> While processing files with ecmascript (for target web.browser):
> 
>    /Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/logger.js:58:11:
>    [BABEL] random.js: Unknown option: /Users/mwhite454/.babelrc.presets
>    at Logger.error
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
>    at OptionManager.mergeOptions
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
>    at OptionManager.addConfig
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
>    at OptionManager.findConfigs
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
>    at OptionManager.init
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
>    at File.initOptions
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:147:75)
>    at new File
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:137:22)
>    at Pipeline.transform
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
>    at
>    /Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/index.js:26:18
>    at Cache.Cp.get
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/cache.js:89:19)
>    at Object.compile
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/index.js:20:23)
>    at Object.Babel.compile (packages/babel-compiler/babel.js:42:1)
>    at packages/babel-compiler/babel-compiler.js:58:1
>    at Array.forEach (native)
>    at BabelCompiler.BCp.processFilesForTarget
>    (packages/babel-compiler/babel-compiler.js:17:1)
> 
>    While processing files with ecmascript (for target os.osx.x86_64):
> 
>    /Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/logger.js:58:11:
>    [BABEL] ecmascript.js: Unknown option: /Users/mwhite454/.babelrc.presets
>    at Logger.error
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
>    at OptionManager.mergeOptions
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
>    at OptionManager.addConfig
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
>    at OptionManager.findConfigs
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
>    at OptionManager.init
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
>    at File.initOptions
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:147:75)
>    at new File
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:137:22)
>    at Pipeline.transform
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
>    at
>    /Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/index.js:26:18
>    at Cache.Cp.get
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/cache.js:89:19)
>    at Object.compile
>    (/Users/mwhite454/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/index.js:20:23)
>    at Object.Babel.compile (packages/babel-compiler/babel.js:42:1)
>    at packages/babel-compiler/babel-compiler.js:58:1
>    at Array.forEach (native)
>    at BabelCompiler.BCp.processFilesForTarget
>    (packages/babel-compiler/babel-compiler.js:17:1)
> 
> => Your application has errors. Waiting for file change.

I'm running this on OS X (10.11.3), with Node v4.4.0 and Mongo 3.2.4

**Comment by lazaridis-com** [comment]
@stubailo @abernix - Looks like an outdated support-request, can be closed.

**Comment by hwillson** [comment]
Agreed - thanks @lazaridis-com!
