### ISSUE TITLE
Isn't Template.body confusing?

### ISSUE THREAD

**Issue by SachaG** [meteor/tutorials#21]
I did the Blaze version of the tutorial recently, and I found it a little bit confusing that it uses `Template.body` when there is no actual template named `body`. I realize this is a special case for the body tag, but I wonder if it's a good idea to introduce special cases at such an early stage? Or am I the only one who found that confusing?

**Comment by stubailo** [comment]
It's not really a special case except that you don't declare it with a <template> tag - in every other way it's identical to a template. Perhaps that is still confusing.

**Comment by SachaG** [comment]
Well that's exactly the part that I'm saying is confusing. If you show me `Template.body.helpers`, then I might assume that I can also do `Template.h1.helpers`. And if later I see `Template.header.helpers`, then is it referring to a template named "header", or to my `<header>` HTML tag?

**Comment by abernix** [comment]
This was updated with additional text in #28.   Do we think this issue can be closed now?

**Comment by lazaridis-com** [comment]
@SachaG - excellent points!
@stubailo @abernix - Issue was fixed with c293fdf, can be closed.
