### ISSUE TITLE
React Tutorial Step 7 missing steps

### ISSUE THREAD

**Issue by william-r-s** [meteor/tutorials#210]
The react tutorial step 7 is missing several steps needed to switch the app to using meteor methods on the client side using Meteor.call
https://www.meteor.com/tutorials/react/publish-and-subscribe

Looks like the code for the missing steps is in the following commits:
https://github.com/meteor/simple-todos-react/commit/fcbc3d45129ac89b7f8d1ee6f26afd39ddb40627
https://github.com/meteor/simple-todos-react/commit/3221bda8001ba4aa18d5768998b6fe2cd2bf6042
https://github.com/meteor/simple-todos-react/commit/b19f696e1a27567ef231568b92db53cf3a2247d9

**Comment by Sheldonfrith** [comment]
thanks for those links William. I'm working through the tutorial right now and this got me unstuck.

**Comment by filipenevola** [comment]
Hey @william-r-s @Sheldonfrith , thank you for your feedback.

I have incorporated your feedback here in this new repo, the new home of react tutorial.

meteor/react-tutorial (react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
