### ISSUE TITLE
Tutorial about vue.js and meteor states to use option --blaze

### ISSUE THREAD

**Issue by silkentrance** [meteor/tutorials#217]
The actual option should be ``--vue``.

See https://www.meteor.com/tutorials/vue/creating-an-app

```
meteor create simple-todos --blaze
```

which should read

```
meteor create simple-todos --vue
```

**Comment by filipenevola** [comment]
Hi @silkentrance I believe the tutorial was written before --vue was available that is why.

We want to migrate it over.

I believe @chris-visser is busy so any help would be appreciated.
https://github.com/meteor/tutorials/issues/213

**Comment by filipenevola** [comment]
It's updated now https://vue-tutorial.meteor.com/simple-todos/01-creating-app.html#1-2-Create-Meteor-Project
