### ISSUE TITLE
simple-todos Tutorial: css didn't deploy properly

### ISSUE THREAD

**Issue by karlsanford** [meteor/tutorials#23]
The css loads properly locally, but when i deployed this is the css that loaded:

body {
    font-family: sans-serif;
    background-color: #315481;
    background-image: linear-gradient(to bottom, #315481, #918e82 100%);
    background-attachment: fixed;
    position: absolute;
    top: 0;
    bottom: 0
}

li.checked > span {
    text-decoration: line-through
}

See local vs server below:

![image](https://cloud.githubusercontent.com/assets/8247493/12805103/688df79c-cabe-11e5-919c-937302c028cc.png)

**Comment by stubailo** [comment]
That's odd! Never seen that before.

Did you try deploying again? If it happens every time, then it will be easier to diagnose.

**Comment by karlsanford** [comment]
I tried to deploy to the same URL and got an authentication error. Deployed to new URL (karlstodoapp2.meteor.com) and the works correctly now.

**Comment by lazaridis-com** [comment]
@karlsanford @stubailo @abernix - issue can be closed.

**Comment by hwillson** [comment]
Agree with closing - thanks @lazaridis-com!
