### ISSUE TITLE
use ReactDOM.render() and findDOMNode() instead of deprecated React.render() and findDOMNode throughout the tutorial

### ISSUE THREAD

**Issue by nsfinkelstein** [meteor/tutorials#24]
Using react developer tools, I see issues like the following:

> Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead

**Comment by joevus** [comment]
+1

**Comment by joevus** [comment]
Just saw they address this is issue [#15](https://github.com/meteor/tutorials/issues/15). You can replace React.render with ReactDOM.render in the simple-todos-react.jsx file.

**Comment by lazaridis-com** [comment]
@joevus @stubailo @abernix - Please close this Issue as "Duplicate"

**Comment by hwillson** [comment]
Thanks @lazaridis-com - closing.
