### ISSUE TITLE
'Select All' button for CSS does not work

### ISSUE THREAD

**Issue by jiaweizhang** [meteor/tutorials#25]
https://www.meteor.com/tutorials/blaze/templates

The 'Select All' button in the top right of the code for box the CSS does not work. It would be nice if all of the code boxes had select all functionality

**Comment by jiaweizhang** [comment]
I'm using Chrome

**Comment by stubailo** [comment]
Interesting, it works in my chrome.

What exact build of chrome are you on? (you can find this through help > about google chrome)

And which operating system?

**Comment by jiaweizhang** [comment]
Version 48.0.2564.82 (64-bit)

Linux Mint 17.3

**Comment by stubailo** [comment]
Hmm, I'm on 48.0.2564.109 (64-bit)

Maybe it's something about Linux.

**Comment by lazaridis-com** [comment]
@stubailo @abernix - can be closed (there is no "select all" button anymore).

**Comment by hwillson** [comment]
Closing - thanks @lazaridis-com!
