### ISSUE TITLE
autopublish has to be installed for tutorial to work

### ISSUE THREAD

**Issue by MichaelVoelkel** [meteor/tutorials#26]
Hi,

I have tried the tutorial up to https://www.meteor.com/tutorials/blaze/collections

with a fresh Windows installation of meteor (v1.2.1). I had no output here after the database insert statement because publish/subscribe is introduced somewhat later in the tutorial and autopublish does not seem to be installed per default in the Windows installer.

(I did not do a system restart because I got my environment variable to work anyways, if that's the issue.)

> meteor add autopublish

enables the output. Also, if I add subscribe/publish to the example code, it will work, as well. Just following the tutorial without autopublish does not work, though, so I get no list.

All the best, Michael

**Comment by stubailo** [comment]
Every new meteor app comes with autopublish pre installed. Did you start your app by typing "meteor create"?

**Comment by MichaelVoelkel** [comment]
Like the tutorial says, I created the simple todo example app:

`meteor create --example simple-todos`

I would always start it by navigating into the simple-todos subdirectory and then simply typing:

`meteor`

Afterwards I manipulated it by exchanging the js and html file like the tutorial says in step 2. Then, I exchanged the js file one time further in step3.

The content of the packages file (comments excluded here) is:

```
accounts-ui
accounts-password
standard-minifiers
meteor-base
mobile-experience
mongo
blaze-html-templates
session
jquery
tracker
logging
reload
random
ejson
spacebars
check
```

Not sure, if some package is supposed to contain autopublish. The example uses publish/subscribe anyways, so it makes even more sense to have autopublish not in there. The way in the tutorial just does not seem to fit.

PS: I had to restart the Windows installer one time, so maybe something got lost there? Seems unlikely, though.

**Comment by stubailo** [comment]
The command in the tutorial doesn't have "--example" in it.

**Comment by MichaelVoelkel** [comment]
That was it... My bad, thanks for clearing!

**Comment by sethgillett** [comment]
This is still a problem that I just ran into doing this tutorial - had to do meteor add autopublish for step 3 to work correctly
