### ISSUE TITLE
.jshintrc to use when following along?

### ISSUE THREAD

**Issue by ghost** [meteor/tutorials#3]
Hi! 
Thanks for a great tutorial. I'm following along and it's clear what's what. 

My editor keeps marking JSHint errors pretty much everywhere since this is a new combo. Do you have a decent .jshintrc to share?

**Comment by stubailo** [comment]
I've been using ESLint recently; here is one that should work for the ES2015 code for the React tutorial: https://github.com/meteor/meteor/blob/devel/scripts/admin/eslint/.eslintrc

**Comment by ghost** [comment]
Thanks, will check it out.
