### ISSUE TITLE
List bullets different color - React Tutorial

### ISSUE THREAD

**Issue by joevus** [meteor/tutorials#32]
In step 2, my result looked different enough from what it's supposed to look like that I examined each line of code to see if any thing was missing. I don't think any thing is missing. Still not sure whether I did something wrong, but don't think I did. If different results may vary in color, may be helpful to say that.
Mine:
![image](https://cloud.githubusercontent.com/assets/13547828/13360461/a8f0e9d8-dc76-11e5-9cce-b580dc1a9aac.png)
What it said it was supposed to look like:
![image](https://cloud.githubusercontent.com/assets/13547828/13360471/b945c114-dc76-11e5-997a-0c2aa4b34363.png)

**Comment by jiaweizhang** [comment]
This is because you didn't add the CSS. Try adding the provided CSS and everything should look the same.

**Comment by stubailo** [comment]
No it's just because the example in the tutorial isn't an image, it's just some rendered markdown. The intention is that it should look like the above. Sorry if that was confusing, perhaps we should include an image instead.

**Comment by joevus** [comment]
I think it's not too big of a deal, not big priority. It was a bit confusing to me but I got over it. Thanks for being responsive.

**Comment by lazaridis-com** [comment]
@stubailo, this should be corrected, I was wondering myself (without looking into this). A tutorial should show **exactly** what the user sees (or at least mention that it will be without formatting).
