### ISSUE TITLE
Error: EPERM, mkdir

### ISSUE THREAD

**Issue by eravas** [meteor/tutorials#33]
![error eper mkdir](https://cloud.githubusercontent.com/assets/17417342/13589039/c157bec8-e4a2-11e5-9972-ed0939019bce.PNG)
i'm getting this error every time I try to create the app.
i'm competley new to this and don't know what to do.
please help.

**Comment by stubailo** [comment]
Where are you running the command from? It's weird that it's trying to put stuff in your system32 folder, and that should fail because the app doesn't have permission to write there.

**Comment by eravas** [comment]
i'm running the command from cmd.exe

**Comment by stubailo** [comment]
What directory?

**Comment by eravas** [comment]
uhh... i'm not entirely sure...

**Comment by stubailo** [comment]
Ah. I think when you open CMD, it starts out in some weird location. You probably want to use `cd` to navigate to your user directory:

http://www.digitalcitizen.life/command-prompt-how-use-basic-commands

**Comment by eravas** [comment]
ok thanks :)
