### ISSUE TITLE
Process-repo script not updating new changes

### ISSUE THREAD

**Issue by ShavonnahTiera** [meteor/tutorials#34]
Hey there!

I left out naming a step in my code repo and when I came back to run the script, the generated log doesn't have the updated info, so it's not showing that step in the viewer. 

The changes were pushed to git and show up on my git log. Is there some sort of cache that I need to clear to regenerate the updated data?

**Comment by stubailo** [comment]
@ShavonnahTiera the script in this repo only works for the tutorials here, since it has the names hardcoded in. You can update the patch file using this command: http://meteor-tutorial-tools.readthedocs.org/en/latest/tutorial-step-diff-compiler/#creating-a-multipatch-file

```
git format-patch --stdout $(git log --pretty=format:%H|tail -1) > tutorial-name.multi.patch
```
