### ISSUE TITLE
What is wrong with this code?

### ISSUE THREAD

**Issue by eravas** [meteor/tutorials#35]
![image](https://cloud.githubusercontent.com/assets/17417342/13937773/28b9720e-ef9e-11e5-8c8a-b82ac0dd8a1d.png)

**Comment by stubailo** [comment]
Probably the `},` on line 94. Weird that the error isn't correct though.

**Comment by eravas** [comment]
ok i will remove the }

**Comment by lazaridis-com** [comment]
@LordoftheWild @stubailo , please close this issue.

**Comment by hwillson** [comment]
Issue has been resolved - closing (thanks @lazaridis-com!).
