### ISSUE TITLE
Simple-todos-angular doesn't build

### ISSUE THREAD

**Issue by ArtfulOne** [meteor/tutorials#37]
I'm new so could be overlooking something. I ran the first one, simple todos, without a problem. Then I tried the second one:

meteor simple-todos-angular

Nothing got created. All I got was a screen describing meteor syntax. 

What did I do wrong?

Thanks,
Arthur

**Comment by Urigo** [comment]
WIth the simple-todos-angular the tutorial still instructs you to run `meteor create simple-todos`:
https://www.meteor.com/tutorials/angular/creating-an-app

Then to run the app all you need to do is:

```
cd simple-todos
meteor npm install
meteor
```

Is that working for you?

**Comment by ArtfulOne** [comment]
Yes, that works without a hitch, and incidentally that app is nice and
pretty. It's the next part that I had problems with:

meteor create simple-todos-angular

That returns the message "unknown option", followed by text explaining the
syntax.

Thanks for the quick response.

Arthur

**Comment by Urigo** [comment]
@ArtfulOne can you point me to the place where it says to do `meteor create simple-todos-angular` ?
I haven't found it in the tutorial..

**Comment by ArtfulOne** [comment]
Uri,

Oddly enough, I can't locate it again either. But there is an item on the
side menu, beneath Tutorials,titled  ToDo App With Angular, so I'm guessing
that it does exist somewhere. I should have left the page open, but sadly
did not.

Thanks for the even quicker response. Much appreciated.

Arthur

**Comment by Urigo** [comment]
ok, I'm closing this now but feel free to re-open and ping me if you find another issue
