### ISSUE TITLE
Hi, the meteor create simple-todos not work fine

### ISSUE THREAD

**Issue by jairorudas** [meteor/tutorials#38]
Hi, the command 'meteor create simple-todos' not work fine, it´s not  building all directories and files that tutorial teaches.
Create only three files, simple-todos.css, simple-todos.js, simple-todos.html
Thank.

**Comment by Urigo** [comment]
@jairorudas I've just tested the tutorial and it looks fine, are you sure you are using Meteor 1.3 ?
can you share you `.meteor/release` file?

**Comment by znafets** [comment]
using meteor 1.3 but after the 
```
meteor mongo
```
and then
```
db.tasks.insert({ text: "Hello world!", createdAt: new Date() });
```

nothing gets reflected on the localhost:3000

**Comment by Urigo** [comment]
closing as it appears to be working and I haven't received a confirmation from you.
Please feel free to re-open if needed

**Comment by znafets** [comment]
Oh sorry, yes ... I missed an import and felt really stupid ... apologies
