### ISSUE TITLE
Viewing the 1.2.1 based tutorials

### ISSUE THREAD

**Issue by kevinbluer** [meteor/tutorials#40]
Is there still a way to view the 1.2.1 based tutorials? The reason I ask is that I'm currently mid-way through teaching a class on Meteor and a number of the students (whom are on Windows machines) have had issues upgrade to 1.3.

Many thanks in advance :+1:

**Comment by stubailo** [comment]
You can clone and run this app:

https://github.com/meteor/tutorial-viewer

Make sure to `git clone --recursive` to get the submodules! Does that work for you?

**Comment by kevinbluer** [comment]
Literally just spotted that too (so was about to close this issue). Many thanks nonetheless @stubailo!

:ok_hand:

**Comment by stubailo** [comment]
We should probably update that app to have the 1.3 tutorials, and just have a 1.2 branch :]

Glad it worked out!
