### ISSUE TITLE
cordova error while trying to run simple-todos at android

### ISSUE THREAD

**Issue by atz3n** [meteor/tutorials#41]
Hi,

I've followed the instructions of the simple-todos tutorial and wasn't able to run the App on my android device. 
I've got the following error message:

---

_meteorProjectFolderPath_/Meteor/simple-todos$ meteor run android
[[[[[ _meteorProjectFolderPath_/Meteor/simple-todos ]]]]]

=> Started proxy.  
=> Started MongoDB.  
% Failed to install 'cordova-plugin-whitelist':Error: _meteorProjectFolderPath_/Meteor/simple-todos/.meteor/local/cordova-build/platforms/android/cordova/version: 
Command failed with exit code EACCES
    at ChildProcess.whenDone (_homeFolder_/.meteor/packages/meteor-tool/.1.3.0_3.fc5itk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/src/superspawn.js:139:23)
    at ChildProcess.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:818:12)
=> Errors executing Cordova commands:                                              

   While adding plugin cordova-plugin-whitelist@1.2.1 to Cordova project:  
   Error:  
   _meteorProjectFolderPath_/Meteor/simple-todos/.meteor/local/cordova-build/platforms/android/cordova/version:
   Command failed with exit code EACCES
   at ChildProcess.whenDone
   (_homeFolder_/.meteor/packages/meteor-tool/.1.3.0_3.fc5itk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/src/superspawn.js:139:23)
   at ChildProcess.emit (events.js:95:17)
   at Process.ChildProcess._handle.onexit (child_process.js:818:12)

_homeFolder_/.meteor/packages/less/.2.5.6.120kpft++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
ExitWithCode:1

---

When I try to run it again, this message occurs:

---

_homeFolder_/.meteor/packages/meteor-tool/.1.3.0_3.fc5itk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: spawn EACCES
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

---

There seems to be something wrong with cordova.
What could be the problem?

Do you have any advice?

Thanks in Advance.

**Comment by digitalWestie** [comment]
Hi, did you resolve this?

**Comment by lazaridis-com** [comment]
@stubailo @abernix - any comments on this?

**Comment by lazaridis-com** [comment]
Should be solvable by updating cordova, see:

https://issues.apache.org/jira/browse/CB-9090

@hwillson - 3 (reported) users hit on this. Relaying users to the forum/stack-overflow (as sugessted by your processes) does not help the ones that hit on this issue by a search. So added info for solving the issue.

Should be closable now.

**Comment by abernix** [comment]
This should have been resolved when Meteor 1.4.2 [was released](https://github.com/meteor/meteor/blob/devel/History.md#v142-2016-10-25) which updated to Cordova 6.2, and even more so by the update to [Cordova 6.4.0](https://github.com/meteor/meteor/pull/8239) which uses a much much [newer version](https://github.com/meteor/meteor/pull/8239/files#diff-c2e211a20bfc723a905fee0004e1c599L17) of `cordova-plugin-whitelist`.

If you're still experiencing problems with this, please open an issue with a reproduction on the [main Meteor GitHub repository](https://github.com/meteor/meteor/).  Thanks!
