### ISSUE TITLE
Blaze tutorial 02, css file name

### ISSUE THREAD

**Issue by afriestad** [meteor/tutorials#43]
In the templates tutorial for Blaze, you are instructed to copy a blob of CSS into the `simple-todos.css` file, however this file isn't included in the automatically generated project. Putting the css into `main.css` seems to have done the intended thing.

Perhaps the filename in the tutorial should be changed?

**Comment by stubailo** [comment]
Yes, it should, we just accepted a PR for this change. Going to republish now.

**Comment by lazaridis-com** [comment]
@stubailo @hwillson - can be closed.

**Comment by hwillson** [comment]
Great @lazaridis-com - thanks!

**Comment by lazaridis-com** [comment]
Hey @hwillson, no need to thank me for such trivialities. Or thank me with a "button", thus I can close the issues myself (many are totally obvious closed, and @stubailo has a tendency to not close the issues in the tracker).

**Comment by hwillson** [comment]
Ha - trivialities or not, it's still appreciated! As for thanking you with access to close these issues yourself, that's not something I can do. I'm not part of MDG - I'm just a big Meteor fan that tries to help out where I can. Right now I'm aiming to chip in a bit of time to help clear out the issues/PR's here that you've flagged, but that help will definitely be a trickle for now (I'm out on vacation this week). Thanks again!
