### ISSUE TITLE
imports/ui/body.js line 3 import '/body.html';

### ISSUE THREAD

**Issue by theoptips** [meteor/tutorials#44]
had to use import '/body.html';
 import './body.html'; produced a screenshot below
file tree attached as well
![screen shot 2016-04-01 at 9 56 52 am](https://cloud.githubusercontent.com/assets/3044801/14214133/2dc834ce-f7f0-11e5-99d6-48cbc9b55df0.png)
![screen shot 2016-04-01 at 9 44 46 am](https://cloud.githubusercontent.com/assets/3044801/14214134/2dcacf18-f7f0-11e5-9cbe-a244dab40b49.png)

**Comment by stubailo** [comment]
I think the `body.html` in the root is extra. You can see by browsing the commit (linked from the tutorial in the code snippet box) what the state of the project should look like after each step: https://github.com/meteor/simple-todos/tree/99cffc464f80899ce34cf446179e8041c9f5114c
