### ISSUE TITLE
Step 11.4 - avoids invoking Meteor.userId()

### ISSUE THREAD

**Issue by cchewar** [meteor/tutorials#46]
This test case passes, but only because the task is not private, thus preventing the evaluation of the second part of the condition (imports/api/tasks.js, line 40) in which Meteor.userId() would be invoked causing an error.  Remove the "task.private &&" or add a taskId.private = true, and you'll see the error:

"Meteor.userId can only be invoked in method calls. Use this.userId in publish functions."

It would be great to have an example that can be extended for inserting tasks, etc.  Otherwise, this is an excellent introduction!

**Comment by electr0sheep** [comment]
I ran into the same issue. To correct it (I believe) replace
`Meteor.userId()`
with
`this.userId`

**Comment by tmeasday** [comment]
@stubailo do you agree we should just not use `Meteor.userId` in methods?

**Comment by stubailo** [comment]
Agreed!

**Comment by tmeasday** [comment]
@Urigo I've done this for the Blaze and React tutorials. I was going to do it for the Angular one but noticed it's slightly different. Do you want me to have a go or would you prefer to handle it?

**Comment by 2624789** [comment]
Hi, I'm following the blaze tutorial.

If I use `Meteor.userId()` in the methods (I made a little change for deleting only own tasks, even if publics)

`if(tarea.dueño !== Meteor.userId()) {
   throw new Meteor.Error('no-autorizado');
}`

The app works, but the test is not passing and gets me the error `"Meteor.userId can only be invoked in method calls. Use this.userId in publish functions."`

If I change `Meteor.userId()` for `this.userId`, the app still works but the test not pass, and now I get `Error: [no-autorizado]`. Logged to console `this.userId` and is `undefined`. What is wrong?

Is there a way for getting the app working and tests passing?

Thanks :)

**Comment by tmeasday** [comment]
Hey @lenieto3 - are you passing in an invocation with a `userId` like `deleteTask.apply(invocation, [taskId]);` ?

**Comment by 2624789** [comment]
Yes, I'm doing it as the tutorial says. This is the test I have

```
  describe('Métodos', () => {

      const usuarioId = Random.id();
      let tareaId;

      beforeEach(() => {
        Tareas.remove({});
        tareaId = Tareas.insert({
          texto: 'tarea de prueba',
          fechaCreacion: new Date(),
          dueño: usuarioId,
          nombreDueño: 'pericles',
          privada: true,
        });
      });

      it('puede eliminar tarea propia', () => {
        const eliminarTarea = Meteor.server.method_handlers['tareas.eliminar'];
        const invocation = { usuarioId };

        eliminarTarea.apply(invocation, [tareaId]);

        assert.equal(Tareas.find().count(), 0);
      });

    });
```

**Comment by electr0sheep** [comment]
So, if you changed the app to only allow the creator of a list to delete it, in the test, you would have to log in as the lists creator. Try changing it so any user can delete a list and it should work. Otherwise, you need to modify the test.
Bottom line: Unless I am mistaken, if this.userId is undefined, that means no one is currently logged in.

**Comment by 2624789** [comment]
Thanks @electr0sheep, I changed it so any user can delete a task. The test is green, but I'm still getting `this.userId => undefined`.

How can I log in a user in the test?

**Comment by electr0sheep** [comment]
Interesting. In the test you create a userId with this line `const usuarioId = Random.id();`
So, if you `console.log(usuarioId);` in the test, and `console.log(this.userId)` in the method you are testing i.e. tareas.eliminar, it should print the same value both times.

The tutorial (at least the English version) recently changed, I believe. I will post the code that I use that tests correctly, even with the deletion restriction.

# tasks.test.js:

``` javascript
/* eslint-env mocha */

import { Meteor } from 'meteor/meteor';
import { Random } from 'meteor/random';
import { assert } from 'meteor/practicalmeteor:chai';

import { Tasks } from './tasks.js';

if (Meteor.isServer) {
  describe('Tasks', () => {
    describe('methods', () => {
      const userId = Random.id();
      console.log ("USER ID IN TEST: " + userId);
      let taskId;

      beforeEach(() => {
        Tasks.remove({});
        taskId = Tasks.insert({
          text: 'test task',
          createdAt: new Date(),
          owner: userId,
          username: 'tmeasday',
        });
      });

      it('can delete owned task', () => {
        // Find the internal implementation of the task method so we can
        // test it in isolation
        const deleteTask = Meteor.server.method_handlers['tasks.remove'];

        // Set up a fake method invocation that looks like what the method expects
        const invocation = { userId };

        // Run the method with `this` set to the fake invocation
        deleteTask.apply(invocation, [taskId]);

        // Verify that the method does what we expected
        assert.equal(Tasks.find().count(), 0);
      });
    });
  });
}
```

# tasks.js:

``` javascript
...
'tasks.remove'(taskId) {
    check(taskId, String);

    const task = Tasks.findOne(taskId);
    console.log("USER ID: " + this.userId);
    if (task.owner !== this.userId) {
      // Make sure only the owner can delete a task
      throw new Meteor.Error('not-authorized');
    }

    Tasks.remove(taskId);
  },
...
```

NOTE: The above code contains the console.log tests I did, just to show you what I was describing earlier.

Finally, I don't know much about programming in different languages. I assume you would still use this.userId, and not this.usuarioId, but I can't be 100% sure. All I know is, if this.userId (or this.usuarioId???) is undefined, then that means there isn't a current user logged in, which means it won't delete it with the restriction.

**Comment by 2624789** [comment]
Programming in different languages is quite the same, you just declare your functions/variables with meaningful names in your language.

I'm using almost the same lines, but I can't get it to work. `this.userId` is **undefined**, so it means there isn't a current user logged in. ¿How could I solve this?

## tareas.js

``` JavaScript
...
'tareas.eliminar'(tareaId) {'tareas.eliminar'(tareaId) {
    check(tareaId, String);

    const tarea = Tareas.findOne(tareaId);

    console.log("DUEÑO TAREA: " + tarea.dueño);
    console.log("DUEÑO TAREA: " + tarea.nombreDueño);
    console.log("USUARIO ID: " + this.userId);
    if(tarea.dueño !== this.userId) {
      throw new Meteor.Error('no-autorizado');
    }

    Tareas.remove(tareaId);
},
...
```

## tareas.tests.js

``` JavaScript
/* eslint-env mocha */

import { Meteor } from 'meteor/meteor';
import { Random } from 'meteor/random';
import { assert } from 'meteor/practicalmeteor:chai';

import { Tareas } from './tareas.js';

if (Meteor.isServer) {
  describe('Tareas', () => {
    describe('métodos', () => {
      const usuarioId = Random.id();
      console.log ("USUARIO ID EN TEST: " + usuarioId);
      let tareaId;

      beforeEach(() => {
        Tareas.remove({});
        tareaId = Tareas.insert({
          texto: 'texto tarea',
          fechaCreacion: new Date(),
          dueño: usuarioId,
          nombreDueño: 'siniestro',
        });
      });

      it('puede eliminar una tarea propia', () => {
        const eliminarTarea = Meteor.server.method_handlers['tareas.eliminar'];
        const invocation = { usuarioId }

        eliminarTarea.apply(invocation, [tareaId]);

        assert.equal(Tareas.find().count(), 0);
      });
    });
  });
}
```

**Comment by tmeasday** [comment]
```
const invocation = { usuarioId }
```

Should be

```
const invocation = { userId: usuarioId }
```

**Comment by 2624789** [comment]
Thanks a lot @tmeasday

**Comment by lazaridis-com** [comment]
@stubailo @hwillson - can be closed.

**Comment by hwillson** [comment]
Thanks @lazaridis-com - closing.
