### ISSUE TITLE
Confusion at React Tutorial Step 4.1

### ISSUE THREAD

**Issue by hammannja** [meteor/tutorials#48]
React Tutorial Step 4.1 is very confusing.
1. Is this modification supposed to take place in main.html or imports/ui/App.jsx?
   a. If main.html, does the modification replace everything else (including div id="render-target"></div>)?
   b. If imports/ui/App.jsx, then where should this be placed (e.g., after all of the other code)?
2. The first line shown (line 18) is "div className="container">", does not reflect a "diff" blue highlighting, and yet this line has not been previously disclosed.
   a. Where should the div className="container"> begin and where should it end (i.e., what are the proper boundaries of the container)?
   b. Should div id="render-target"></div> (in main.html) be inside the container, outside it, or does in not matter?
3. At line 31, there is a ul> outside of the header and not within a body> tag. What is that? Is it an error? This line also has not been previously disclosed.

Thanks!

**Comment by stubailo** [comment]
You can click on the filename to see the full commit. Here is the diff on GitHub:

https://github.com/meteor/simple-todos-react/commit/b595a90b125e15632f84bbe16f7d46e1682418a0

And here's the full file, `App.jsx`:

https://github.com/meteor/simple-todos-react/blob/b595a90b125e15632f84bbe16f7d46e1682418a0/imports/ui/App.jsx

The elements you're referring to as "not previously disclosed" were added in step 2.4, here: https://github.com/meteor/simple-todos-react/commit/ccf6c7a8a47ee9899d60d1b2b82eb2de32c89513

Perhaps you accidentally switched between the React and Blaze tutorials half-way?

**Comment by hammannja** [comment]
Sorry, now see that! Thanks!
