### ISSUE TITLE
Update and Delete from tutorial doesn't display my data, nor are the new functionalities there

### ISSUE THREAD

**Issue by brianwphamSF** [meteor/tutorials#56]
It seems when I add in this code along with what I already have, my todo-list goes blank and it doesn't function properly. Please look into this issue!

EDIT: I got it, it's required to first remove the code from the body.html portion in templates. It's fine for actual developers who are experienced, but probably better to add in a couple more lines about that for actual beginners.

**Comment by stubailo** [comment]
Have you looked at the full contents of the app at that step on GitHub? Then you can compare your code to the desired code, and see where it's different.

**Comment by stubailo** [comment]
(If you tell me what step it is, I can get you a link)
