### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by godavem** [meteor/tutorials#60]
Todos App > 1. Creating your first app > ES2015 JavaScript features > first paragraph: 
"This is <missing "why"?> Meteor ships by default with support..."

Todos App > Figure 7.1  Add hide-completed checkbox to HTML:
I think the closing tag on the head section is missing. (~line 5)

**Comment by lazaridis-com** [comment]
"because" was added.

7.1 looks fine.

@hwillson - can be closed.

**Comment by hwillson** [comment]
Great - closing - thanks @lazaridis-com!
