### ISSUE TITLE
a mistake

### ISSUE THREAD

**Issue by XWC0313** [meteor/tutorials#61]
In "Checking off and deleting tasks"
5.3，line 5 
**_import './task.html';_**  should be  **_'import ./body.html';_**

**Comment by lazaridis-com** [comment]
body.js imports task.js which imports. task.html -> all fine. Verified in code, too.

@hwillson - can be closed, "worksforme" or "invalid"

**Comment by abernix** [comment]
I think @lazaridis-com is correct and that this is fine (or already fixed – though I can't find any record in the commit history of it ever being wrong).

If you happen upon this bug again, please consider making a [pull request](https://github.com/meteor/tutorials/pulls) which makes it even easier to find and fix! 😄
