### ISSUE TITLE
React Error

### ISSUE THREAD

**Issue by ninjasort** [meteor/tutorials#72]
Getting this error when adding a checkbox to Tasks.

Task is changing an uncontrolled input of type checkbox to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component

**Comment by renanlecaro** [comment]
It seems to be a problem with react when it is given the prop `checked={undefined}`, it doesn't like it for some reason. We could either  use something like `checked={this.props.task.checked || false}` or initialise inserted tasks with `checked:false`

**Comment by ninjasort** [comment]
No worries. Closing this for now.

**Comment by t3db0t** [comment]
Strongly recommend the tutorial is amended to initialize task insertion with ```checked: false```. You don't want the tutorial to show ANY errors or warnings, it is extremely distracting to the student, and can drastically reduce confidence in the product.
