### ISSUE TITLE
React Todos Chapter 2 Mistake

### ISSUE THREAD

**Issue by skoontastic** [meteor/tutorials#75]
After creating the three new files, the guide says:

> Some initialization code (in our **client/main.js** client JavaScript entrypoint)...

I'm guessing that's supposed to say **client/main.jsx**.

**Comment by abernix** [comment]
Yes, it was meant to be `jsx`.  Thanks, @skoontastic.  Sorry we took so long to fix this.

Thanks for the pull-request fix in #114, @lazaridis-com.
