### ISSUE TITLE
Blaze 8.3 Configure accounts-ui - username only

### ISSUE THREAD

**Issue by richardwo** [meteor/tutorials#76]
Following the steps in this section `passwordSignupFields: 'USERNAME_ONLY'` appears to make no difference to the sign in/register forms which still ask for email address.
Edit: Sorry - please delete this, just read the next step 8.4 and realised that's what is necessary to make the change appear.

**Comment by ghost** [comment]
I have some issues when using  accounts-ui and accounts-password while doing the meteor tutorial. If I use the config options for the accounts-ui package as related into the Blaze tutorial, step 8.3,  I have this problem, but while using the package without configure options, the app seems to run properly.

My platform: Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

>  in the root directory of your application.
> /home/fernando/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
> 						throw(ex);
> 						^
> 
> TypeError: Cannot read property 'config' of undefined
>     at meteorInstall.imports.startup.accounts-config.js (imports/startup/accounts-config.js:3:1)
>     at fileEvaluate (packages/modules-runtime.js:188:9)
>     at Module.require (packages/modules-runtime.js:111:16)
>     at Module.Mp.import (/home/fernando/.meteor/packages/modules/.0.7.7.1m2ukcu++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
>     at meteorInstall.server.main.js (server/main.js:1:1)
>     at fileEvaluate (packages/modules-runtime.js:188:9)
>     at require (packages/modules-runtime.js:111:16)
>     at /home/fernando/Documentos/dev/comet/.meteor/local/build/programs/server/app/app.js:47:1
>     at /home/fernando/Documentos/dev/comet/.meteor/local/build/programs/server/boot.js:295:34
>     at Array.forEach (native)
> Exited with code: 1

The code into imports/startup/accounts-config.js

```
import { Accounts } from 'meteor/accounts-base';
 
Accounts.ui.config({
  passwordSignupFields: 'USERNAME_ONLY',
});

```
and in client/main.js

`import '../imports/startup/accounts-config.js';`

This is the list of packages:

accounts-password      1.3.3  Password support for accounts
accounts-ui            1.1.9  Simple templates to add login widgets to an app
autopublish            1.0.7  (For prototyping only) Publish the entire database to all clients
blaze-html-templates   1.0.5  Compile HTML templates into reactive UI with Meteor Blaze
ecmascript             0.6.1  Compiler plugin that supports ES2015+ in all .js files
es5-shim               4.6.15  Shims and polyfills to improve ECMAScript 5 support
insecure               1.0.7  (For prototyping only) Allow all database writes from the client
jquery                 1.11.10  Manipulate the DOM using CSS selectors
meteor-base            1.0.4  Packages that every Meteor app needs
mobile-experience      1.0.4  Packages for a great mobile user experience
mongo                  1.1.14  Adaptor for using MongoDB and Minimongo over DDP
reactive-dict          1.1.8  Reactive dictionary
reactive-var           1.0.11  Reactive variable
shell-server           0.2.1  Server-side component of the `meteor shell` command.
standard-minifier-css  1.3.2  Standard css minifier used with Meteor apps by default.
standard-minifier-js   1.2.1  Standard javascript minifiers used with Meteor apps by default.
tracker                1.1.1  Dependency tracker to allow reactive callbacks

**Comment by lazaridis-com** [comment]
@ghost, can you please open a new issue if this is still actual?

>Edit: Sorry - please delete this, just read the next step 8.4 and realised that's what is necessary to make the change appear.

@hwillson - the initial issue is a false alarm.

**Comment by lazaridis-com** [comment]
@ghost (and others who run into this)

"You need to add the config on client side code :"
http://stackoverflow.com/questions/38647334/meteor-cannot-read-property-config-of-undefined

**Comment by abernix** [comment]
> Edit: Sorry - please delete this, just read the next step 8.4 and realised that's what is necessary to make the change appear.

Closing per this edit on the original post.  Glad you got it figured out!
