### ISSUE TITLE
A few minor issues.

### ISSUE THREAD

**Issue by FranciscoBarros** [meteor/tutorials#8]
1) Simple Todos React Tutorial, Step 8
Text:
One more feature: Showing a count of incomplete tasks
... Since we already have the data in the client-side Minimongo collection
Comment:
Minimongo is mentioned but never presented in earlier tutorial's steps.
Tutorial may be first React's user reading.

2) Simple Todos React Tutorial, Step 10
Text:
... we will discuss this a bit later in the section titled Latency compensation.
Comment:
Section name is Optimistic UI.

3) Simple Todos React Tutorial, Step 10
Text:
2. We can add extra validation logic to setChecked and deleteTask in later steps when users can make tasks private
Comment:
deleteTask is, actually, named as removeTask.

**Comment by stubailo** [comment]
Awesome, thanks for the feedback! I'll fix these tomorrow.

**Comment by lazaridis-com** [comment]
@stubailo @abernix (who to ping on doc issues?)

I guess this one can be closed?

**Comment by hwillson** [comment]
Thanks @lazaridis-com - I've taken a look; I don't think we should close this one yet (the suggestions made in the original issue are still valid and haven't been implemented yet).

**Comment by lazaridis-com** [comment]
@hwillson, I'll workout a PR in the next hours (would like to test some PR-mechanics anyway).

**Comment by lazaridis-com** [comment]
@hwillson, this should do it.

**Comment by abernix** [comment]
I do believe these are all covered now!
