### ISSUE TITLE
React tutorial Errors Prevented Startup

### ISSUE THREAD

**Issue by rfines** [meteor/tutorials#82]
I am trying to learn the basics of Meteor with React using Meteor version 1.4.1.1 on a MacBook Pro. 
I ran 

```
meteor create simple-todos 
```

and followed the first few steps in the tutorial but the app would not start to begin with giving me the following console output:

> [[[[[ ~/Projects/samples/working-maybe ]]]]]
>      => Started proxy.
>      => Started MongoDB.
>       /Users/rfines/Projects/samples/working-    maybe/.meteor/local/build/programs/server/boot.js:333
>       }).run();
>       ^
>      TypeError: module.import is not a function
>  at meteorInstall.node_modules.meteor.webapp.webapp_server.js   (/Users/rfines/Projects/samples/working-maybe/.meteor/local/build/programs/server/packages/webapp.js:33:26)
> at fileEvaluate (packages/modules-runtime/packages/modules-runtime.js:160:1)
> W20160830-13:30:47.928(-5)? (STDERR)     at require (packages/modules-runtime/packages/modules-runtime.js:89:1)
> W20160830-13:30:47.928(-5)? (STDERR)     at /Users/rfines/Projects/samples/working-maybe/.meteor/local/build/programs/server/packages/webapp.js:829:1
> W20160830-13:30:47.930(-5)? (STDERR)     at /Users/rfines/Projects/samples/working-maybe/.meteor/local/build/programs/server/packages/webapp.js:842:3
> W20160830-13:30:47.930(-5)? (STDERR)     at /Users/rfines/Projects/samples/working-maybe/.meteor/local/build/programs/server/boot.js:292:10
> W20160830-13:30:47.930(-5)? (STDERR)     at Array.forEach (native)
> W20160830-13:30:47.931(-5)? (STDERR)     at Function._.each._.forEach (/Users/rfines/.meteor/packages/meteor-tool/.1.4.1_1.1xaxxg3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
> W20160830-13:30:47.931(-5)? (STDERR)     at /Users/rfines/Projects/samples/working-maybe/.meteor/local/build/programs/server/boot.js:128:5

I am trying to run this with Meteor 1.4.1.1 with the following steps to reproduce:

```
meteor create test
cd test
meteor
```

even these steps don't work:

```
meteor create test
cd test
meteor npm install
meteor
```

Has anybody had this problem?

**Comment by lazaridis-com** [comment]
@rfines, try removing `~/.meteor` - information picked from:

http://stackoverflow.com/questions/40477149/meteor-build-typeerror-module-import-is-not-a-function

@hwillson - I guess it can be closed.

**Comment by abernix** [comment]
I believe this was a temporary bug at the time that 1.4.1.1 was released and should no longer be a problem on Meteor 1.4.3.2.  Please open a reproduction with [meteor/meteor](https://github.com/meteor/meteor.git) if this problem continues, and thanks for reporting!
