### ISSUE TITLE
Wrong css filename in Todo app with Angular

### ISSUE THREAD

**Issue by peterkuiper** [meteor/tutorials#9]
In the section `Adding CSS` a wrong filename is being used `simple-todos.css` instead of `simple-todos-angular.css`

I did a PR, hope that works for you. If you want I can also fix the blaze and react tutorials.

**Comment by peterkuiper** [comment]
Oops, in adding-css.md there is still simple-todos.css hardcoded. This needs to become something like {{#cssFilename "simple-todos.css"}}. Sorry about that, I should have looked better. Do you want me to change the PR?

**Comment by stubailo** [comment]
Yeah, we should add an argument/data context to the `addingCSS` template that lets you set the filename. You can try out the new code by using the tutorial viewer app: https://github.com/meteor/tutorial-viewer

**Comment by peterkuiper** [comment]
Do I need to run packages/tutorials/scripts/process-repo.rb to regenerate?

**Comment by stubailo** [comment]
Nope, that's only if you change the actual code snippets. In this case, we are just changing the content/UI.

**Comment by stubailo** [comment]
BTW, let me know what parts of this are confusing, I want to make it easier to contribute to the tutorials (we only open-sourced this recently, so there hasn't been much action yet)

**Comment by peterkuiper** [comment]
Sure thing, let me work through it. If you want, I can also help document these steps to make it easier for newcomers.

**Comment by stubailo** [comment]
Yeah that would be awesome!

**Comment by stubailo** [comment]
Also, is using the tutorial viewer super hard? Maybe I should just embed that app inside this repo so you don't need to clone a separate thing to test your code.

**Comment by peterkuiper** [comment]
Well, its not easy to figure out how it all works. I'm having problem with the meteor-markdown-templating.  I thought I got it but I'm totally wrong (and thus my PR doesn't make any sense). For instance, what is {{> DiffBox tutorialName="simple-todos-angular" step="9.2"}} and how is it used? Also I can't seem to find references to codeBox. I might be overlooking something but I don't see any options for using variables (for the css filename). Can it perhaps be controlled via metadata.js? If you have some docs on that it would be quite helpful for me to figure this out :)

**Comment by stubailo** [comment]
Are you new to Meteor's templating system?

**Comment by peterkuiper** [comment]
Indeed I am so I'll need a bit more time to get up to speed!

**Comment by peterkuiper** [comment]
I tried this but I am unable to set the cssFilename var in the argument to the codeBox template so it might not be the best solution. What do you prefer/recommend?

```
diff --git a/content/angular/step02.md b/content/angular/step02.md
index d2bcdb2..570fbc1 100644
--- a/content/angular/step02.md
+++ b/content/angular/step02.md
@@ -50,6 +50,6 @@ Everything inside &lt;template> tags is compiled into Meteor _templates_, which

 All of the code in your regular .HTML files is compiled with [Meteor's Spacebars compiler](https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md).

-{{> addingCSS}}
+{{> addingCSS cssFilename="simple-todo-angular.css"}}

 {{/template}}
diff --git a/content/shared/adding-css.md b/content/shared/adding-css.md
index afe9aea..8fa70e9 100644
--- a/content/shared/adding-css.md
+++ b/content/shared/adding-css.md
@@ -4,7 +4,7 @@

 Before we go any further, let's make our app look nice by adding some CSS.

-Since this tutorial is focused on working with HTML and JavaScript, just copy all the CSS code below into `simple-todos.css`. This is all the CSS code you will need until the end of the tutorial. The app will still work without the CSS, but it will look much nicer if you add it.
+Since this tutorial is focused on working with HTML and JavaScript, just copy all the CSS code below into `{{cssFilename}}`. This is all the CSS code you will need until the end of the tutorial. The app will still work without the CSS, but it will look much nicer if you add it.

 {{#codeBox "Replace simple-todos.css with this code"}}
 ```css
```

**Comment by peterkuiper** [comment]
Maybe something like this is more in line with DiffBox:

```
diff --git a/content/angular/step02.md b/content/angular/step02.md
index d2bcdb2..5812d02 100644
--- a/content/angular/step02.md
+++ b/content/angular/step02.md
@@ -50,6 +50,6 @@ Everything inside &lt;template> tags is compiled into Meteor _templates_, which

 All of the code in your regular .HTML files is compiled with [Meteor's Spacebars compiler](https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md).

-{{> addingCSS}}
+{{> addingCSS tutorialName="simple-todos-angular"}}

 {{/template}}
diff --git a/content/shared/adding-css.md b/content/shared/adding-css.md
index afe9aea..2515196 100644
--- a/content/shared/adding-css.md
+++ b/content/shared/adding-css.md
@@ -6,7 +6,7 @@ Before we go any further, let's make our app look nice by adding some CSS.

 Since this tutorial is focused on working with HTML and JavaScript, just copy all the CSS code below into `simple-todos.css`. This is all the CSS code you will need until the end of the tutorial. The app will still work without the CSS, but it will look much nicer if you add it.

-{{#codeBox "Replace simple-todos.css with this code"}}
+{{#codeBox tutorialName=tutorialName description="Copy all the CSS code below into"}}
 ```css
 /* CSS declarations go here */
 body {
```

**Comment by peterkuiper** [comment]
I tried a few solutions but still ran into the problem of not being able to pass a dynamic parameter into a template, ie

```
{{#codeBox "Replace {{cssFilename}} with this code"}}
```

or

```
{{#codeBox "Replace "+cssFilename+" with this code"}}
```

obviously does not work, so what is the best solution? A helper function just for this?

**Comment by peterkuiper** [comment]
Btw, using the tutorial viewer isn't hard and I think keeping it from the tutorials repo makes sense.

**Comment by Urigo** [comment]
That also happens in the `React` tutorial.

**Comment by Urigo** [comment]
Fixed with the new version of the tutorial
