### ISSUE TITLE
Step 2 (Blaze) Spacebars link 404

### ISSUE THREAD

**Issue by jf1x** [meteor/tutorials#93]
On this page: https://www.meteor.com/tutorials/blaze/templates

In the "Adding logic and data to templates" section, the "Meteor's Spacebars compiler" link has a URL of https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md which returns a 404 error.

**Comment by lazaridis-com** [comment]
@abernix @hwillson 
 
2af3f9d fixed #96, but the tutorial online was apparently not updated yet:

https://www.meteor.com/tutorials/blaze/templates

**Comment by abernix** [comment]
This has been merged and will be updated on the live tutorial site in a few hours.  Thanks for reporting this, @jfarquhar.
